### ISSUE TITLE
Implementation of To-Do Home Screen

### ISSUE THREAD

**Issue by sharon2719** [sharon2719/TrackMeApp#1]
- [x] Look for the best UI to be used 
- [ ] Implement the  Home Screen code 
- [ ] Test whether the home screen is working as expected
